#!/bin/bash

case $* in
	'_qwjk12i7ndvi8owe')
  	URL=https://xaoxuu.com/wiki/vim-cn.sh
		printf "\n> \033[32m恭喜您，安装成功！\033[0m已为您打开文档页面，请收藏这个页面，在您遇到问题的时候可以查看文档：\033[32m${URL}\033[0m\n\n"
    open ${URL}
	;;
	*)
		curl -s https://raw.githubusercontent.com/xaoxuu/vim-cn.sh/v2/upload | sh -s $*
	;;
esac
